### ISSUE TITLE
Add isNeitherNullNorUndefined

### ISSUE THREAD

**Issue by maxjanes** [elierotenberg/typed-assert#4]
hi .. first of all, thank you for this very useful library :+1: 

Now, when using this library with strict compiler mode on, it often happens to assert against variables being both null *and* undefined.

Writing two lines for each assertion makes the code unnecessarily verbose, while inventing some workaround or custom assertion makes it less readable ...

it would be great if there was a specialized assert for this use case, something like a self explanatory isNeitherNullNorUndefined.

what do you think ? I can pull request if you think so ...

**Comment by elierotenberg** [comment]
Thank you for your comment!
You can definitely make a PR and I will merge it, but you should know I am personally now using [zod](https://github.com/colinhacks/zod) instead of my own `typed-assert`. While it slightly more complex, it is also much better maintained and designed, and has a growing ecosystem.

**Comment by maxjanes** [comment]
zod looks very interesting, thanks
but, if I got it correctly, zod seems attacking the more general problem of validation of data schemas ... on the other hand, I'm using your library for precondition violation checking, with the bonus of typescript type guards, so it's a somewhat different goal and it works great for me.

ok, I'm going to make a PR thanks ..

**Comment by maxjanes** [comment]
done, please note that I didn't update the package version.

**Comment by elierotenberg** [comment]
#5 is merged, I took the liberty to rename the new assert to `isNotVoid` as it is less verbose yet captures the same idea.
New version is released as 1.0.9.

Thanks a lot for your contribution!
